# Generated by Django 5.2.15 on 2026-06-13 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_order_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="type",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="value",
        ),
        migrations.AddField(
            model_name="contact",
            name="apartment",
            field=models.CharField(blank=True, max_length=15, verbose_name="Квартира"),
        ),
        migrations.AddField(
            model_name="contact",
            name="building",
            field=models.CharField(blank=True, max_length=15, verbose_name="Строение"),
        ),
        migrations.AddField(
            model_name="contact",
            name="city",
            field=models.CharField(default="city", max_length=50, verbose_name="Город"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contact",
            name="house",
            field=models.CharField(blank=True, max_length=15, verbose_name="Дом"),
        ),
        migrations.AddField(
            model_name="contact",
            name="phone",
            field=models.CharField(default=2443, max_length=20, verbose_name="Телефон"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contact",
            name="street",
            field=models.CharField(
                default="fgbgf", max_length=100, verbose_name="Улица"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contact",
            name="structure",
            field=models.CharField(blank=True, max_length=15, verbose_name="Корпус"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="user",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
