# Generated by Django 5.2.15 on 2026-06-11 22:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_category_parameter_shop_alter_user_is_active_contact_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="value",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="productparameter",
            name="value",
            field=models.CharField(max_length=200),
        ),
    ]
