# Generated by Django 5.2.15 on 2026-06-21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_remove_contact_type_remove_contact_value_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="url",
            field=models.URLField(blank=True),
        ),
    ]
