# Generated by Django 5.2.15 on 2026-06-25 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_offer_snapshots_basket_constraints"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает"),
                            ("processing", "В обработке"),
                            ("completed", "Завершён"),
                            ("failed", "Ошибка"),
                        ],
                        default="pending",
                        max_length=15,
                        verbose_name="Статус импорта",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата завершения"
                    ),
                ),
                (
                    "stats",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Статистика"
                    ),
                ),
                (
                    "error_log",
                    models.TextField(blank=True, default="", verbose_name="Лог ошибок"),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_jobs",
                        to="api.shop",
                        verbose_name="Магазин",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача импорта",
                "verbose_name_plural": "Задачи импорта",
                "ordering": ("-created_at",),
            },
        ),
    ]
