"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import logging
import os
from datetime import timedelta
from pathlib import Path
from typing import Any

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

load_dotenv()


# 1. Базовые пути и переменные окружения ----
BASE_DIR = Path(__file__).resolve().parent.parent


def env_bool(name: str, default: bool) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def env_list(name: str, default: str = "") -> list[str]:
    value = os.getenv(name, default)
    return [item.strip() for item in value.split(",") if item.strip()]


# 2. Безопасность ----
DEBUG = env_bool("DJANGO_DEBUG", default=True)

# Настройки кэширования
CACHE_BACKEND = os.getenv("DJANGO_CACHE_BACKEND", "locmem")
CACHE_TIMEOUT_CATALOG = int(os.getenv("DJANGO_CACHE_TIMEOUT_CATALOG", "300"))  # 5 минут

if CACHE_BACKEND == "redis":
    try:
        import redis  # noqa: F401
    except ImportError:
        CACHE_BACKEND = "locmem"
        logging.warning(
            "redis не установлен (pip install redis). Переключение на locmem cache."
        )
    else:
        CACHES = {
            "default": {
                "BACKEND": "django.core.cache.backends.redis.RedisCache",
                "LOCATION": os.getenv("DJANGO_REDIS_URL", "redis://redis:6379/1"),
                "OPTIONS": {
                    "socket_connect_timeout": 2,
                },
            }
        }

if CACHE_BACKEND != "redis":
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "procurement-api-cache",
        }
    }

# 2a. RQ (асинхронная очередь задач) ----
# По умолчанию используем тот же Redis, что и для кэша.
# Если кэш на locmem, RQ всё равно может работать на Redis.
_RQ_REDIS_HOST = "redis"
_RQ_REDIS_PORT = 6379
_RQ_REDIS_DB = 1

RQ_QUEUES = {
    "default": {
        "HOST": os.getenv("DJANGO_RQ_HOST", _RQ_REDIS_HOST),
        "PORT": int(os.getenv("DJANGO_RQ_PORT", str(_RQ_REDIS_PORT))),
        "DB": int(os.getenv("DJANGO_RQ_DB", str(_RQ_REDIS_DB))),
        "DEFAULT_TIMEOUT": 360,
    },
}

SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = "django-insecure-dev-only-change-me"
    else:
        raise ImproperlyConfigured(
            "DJANGO_SECRET_KEY must be set when DJANGO_DEBUG=False."
        )

ALLOWED_HOSTS = env_list(
    "DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1,192.168.137.2,testserver"
)


# 2a. Прокси (code-server / reverse proxy) ----
# code-server проксирует https://192.168.137.2:8080/proxy/8000/ → http://web:8000
# WSGI middleware (core/wsgi.py) динамически устанавливает SCRIPT_NAME при
# обнаружении X-Forwarded заголовков, чтобы все сгенерированные Django URL
# (пагинация, reverse(), Swagger) содержали префикс /proxy/8000.
# Прямые запросы (localhost:8000) работают без префикса — одновременно.

USE_X_FORWARDED_HOST = env_bool("DJANGO_USE_X_FORWARDED_HOST", default=True)
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

_CSRF_ORIGINS = env_list("DJANGO_CSRF_TRUSTED_ORIGINS", "")
if "https://192.168.137.2:8080" not in _CSRF_ORIGINS:
    _CSRF_ORIGINS.append("https://192.168.137.2:8080")
CSRF_TRUSTED_ORIGINS = _CSRF_ORIGINS


# 3. Приложения ----
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "djoser",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "drf_spectacular",
    "django_filters",
    "django_rq",
    "api",
]


# 4. Middleware и URL ----
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "api.middleware.RequestLogMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# 5. База данных ----
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST", "db"),
        "PORT": os.getenv("DB_PORT", "5432"),
    }
}


# 6. Пароли ----
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# 7. Локализация ----
LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# 8. Статика ----
STATIC_URL = "static/"

# Лимит размера загружаемых файлов — защита от OOM при импорте YAML-прайсов
DATA_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024  # 5 MB


# 9. Django REST Framework ----
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",  # Доступ только для авторизованных по умолчанию
    ),
    "DEFAULT_THROTTLE_CLASSES": (
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ),
    "DEFAULT_THROTTLE_RATES": {
        "anon": os.getenv("DJANGO_THROTTLE_ANON", "20/minute"),
        "user": os.getenv("DJANGO_THROTTLE_USER", "60/minute"),
        "shop_register": os.getenv("DJANGO_THROTTLE_SHOP_REGISTER", "5/minute"),
        "shop_import": os.getenv("DJANGO_THROTTLE_SHOP_IMPORT", "10/minute"),
        "order_confirm": os.getenv("DJANGO_THROTTLE_ORDER_CONFIRM", "10/minute"),
    },
}


# 10. OpenAPI ----
SPECTACULAR_SETTINGS = {
    "TITLE": "Procurement API",
    "DESCRIPTION": (
        "API сервиса закупок. Основной сценарий: пользователь регистрируется через "
        "Djoser `POST /api/auth/users/`, активирует аккаунт по uid/token из письма `POST /api/auth/users/activation/`,"
        "получает JWT через `/api/auth/jwt/create/`, передает access token в заголовке "
        "`Authorization: Bearer <token>`, просматривает каталог, добавляет предложения "
        "товаров в корзину через `/api/basket/items/`, сохраняет адрес доставки "
        "через `/api/contacts/` и подтверждает заказ. "
        "Магазин регистрируется через отдельный endpoint `/api/shops/register/`, "
        "после чего администратор одобряет или блокирует заявку магазина через "
        "admin endpoints. "
        "`Product` означает общий товар каталога, `ProductInfo/Offer` - предложение "
        "конкретного магазина с ценой и остатком. Корзина хранится как заказ в "
        "статусе `basket`; история заказов показывает только оформленные заказы. "
        "Все бизнес-эндпоинты `/api/products/`, `/api/offers/`, `/api/basket/`, `/api/contacts/` "
        "и `/api/orders/` требуют JWT-аутентификацию."
    ),
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    "SWAGGER_UI_SETTINGS": {
        "persistAuthorization": True,
        "displayOperationId": True,
        "filter": True,
    },
    # Сервер для Try It Out в Swagger UI.  hook динамически добавляет
    # entry с учётом SCRIPT_NAME (префикс /proxy/8000 для code-server).
    "POSTPROCESSING_HOOKS": [
        "api.openapi.add_server_entry",
    ],
    "TAGS": [
        {
            "name": "Products",
            "description": (
                "Каталог товаров Product и предложения магазинов ProductInfo. "
                "Список возвращает товары, фильтры по цене/магазину/характеристикам "
                "работают через связанные предложения."
            ),
        },
        {
            "name": "Shops",
            "description": (
                "Регистрация магазина и публичные операции поставщика. "
                "Новый магазин получает статус pending до одобрения администратором."
            ),
        },
        {
            "name": "Admin",
            "description": (
                "Административные операции платформы. Доступны только пользователям "
                "с is_staff=True и type=admin."
            ),
        },
        {
            "name": "Basket",
            "description": (
                "Текущая корзина пользователя. Добавление создает basket-заказ при "
                "необходимости, повторное добавление увеличивает quantity, удаление "
                "выполняется по ID позиции OrderItem."
            ),
        },
        {
            "name": "Contacts",
            "description": "Адреса доставки текущего пользователя для подтверждения заказа.",
        },
        {
            "name": "Orders",
            "description": (
                "Подтверждение корзины, история оформленных заказов, детальная "
                "информация с позициями и обновление статуса заказа."
            ),
        },
        {
            "name": "auth",
            "description": "Регистрация, активация пользователей и JWT-токены Djoser.",
        },
    ],
    "ENUM_NAME_OVERRIDES": {
        "OrderStateEnum": "api.models.STATE_CHOICES",
        "OrderUpdateStateEnum": [
            "confirmed",
            "processing",
            "sent",
            "delivered",
            "partially_canceled",
            "canceled",
        ],
        "UserTypeEnum": "api.models.USER_TYPE_CHOICES",
        "ShopStatusEnum": "api.models.SHOP_STATUS_CHOICES",
        "OrderItemStateEnum": "api.models.ORDER_ITEM_STATE_CHOICES",
        "ArchiveStatusEnum": "api.models.ARCHIVE_STATUS_CHOICES",
        "ProductInfoStatusEnum": "api.models.PRODUCT_INFO_STATUS_CHOICES",
    },
}


# 11. JWT и Djoser ----
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
}

AUTH_USER_MODEL = "api.User"

DJOSER = {
    "LOGIN_FIELD": "email",
    "USER_ID_FIELD": "pk",
    "SEND_ACTIVATION_EMAIL": True,
    "ACTIVATION_URL": "activate/{uid}/{token}",
    "SERIALIZERS": {
        "user_create": "api.serializers.UserCreateSerializer",
        "user": "api.serializers.UserSerializer",
        "current_user": "api.serializers.UserSerializer",
    },
}


# 12. Email ----
DEFAULT_FROM_EMAIL = os.getenv("DJANGO_DEFAULT_FROM_EMAIL", "noreply@example.com")

EMAIL_BACKEND: str = os.getenv(
    "DJANGO_EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend",
)

ADMIN_EMAILS = env_list("DJANGO_ADMIN_EMAILS", "admin1@example.com,admin2@example.com")


# 13. Logging ----
DJANGO_LOGGING_ENABLED = env_bool("DJANGO_LOGGING_ENABLED", default=False)
LOG_LEVEL = os.getenv("DJANGO_LOG_LEVEL", "WARNING").upper()
LOG_LEVEL_CHOICES = {"DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"}
if LOG_LEVEL not in LOG_LEVEL_CHOICES:
    raise ImproperlyConfigured(
        "DJANGO_LOG_LEVEL must be one of DEBUG, INFO, WARNING, ERROR or CRITICAL."
    )

DJANGO_LOG_SQL = env_bool("DJANGO_LOG_SQL", default=False)
DJANGO_LOG_MODULES = set(env_list("DJANGO_LOG_MODULES"))
CONSOLE_LOG_LEVEL = "DEBUG" if DJANGO_LOG_SQL else LOG_LEVEL
DISABLED_LOG_LEVEL = "CRITICAL"


def module_log_level(logger_name: str) -> str:
    if not DJANGO_LOGGING_ENABLED:
        return DISABLED_LOG_LEVEL
    if not DJANGO_LOG_MODULES:
        return DISABLED_LOG_LEVEL
    if logger_name in DJANGO_LOG_MODULES:
        return LOG_LEVEL
    for enabled_module in DJANGO_LOG_MODULES:
        if logger_name.startswith(f"{enabled_module}."):
            return LOG_LEVEL
    return DISABLED_LOG_LEVEL


LOGGING: dict[str, Any] = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": (
                "%(asctime)s %(levelname)s %(name)s %(module)s:%(lineno)d %(message)s"
            )
        },
        "simple": {
            "format": "%(levelname)s %(name)s %(message)s",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
            "level": CONSOLE_LOG_LEVEL,
        },
    },
    "root": {
        "handlers": ["console"],
        "level": LOG_LEVEL if DJANGO_LOGGING_ENABLED else DISABLED_LOG_LEVEL,
    },
    "loggers": {
        "api": {
            "handlers": ["console"],
            "level": module_log_level("api"),
            "propagate": False,
        },
        "api.request": {
            "handlers": ["console"],
            "level": module_log_level("api.request"),
            "propagate": False,
        },
        "django": {
            "handlers": ["console"],
            "level": module_log_level("django"),
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console"],
            "level": (
                "ERROR"
                if module_log_level("django.request") != DISABLED_LOG_LEVEL
                else DISABLED_LOG_LEVEL
            ),
            "propagate": False,
        },
        "django.server": {
            "handlers": ["console"],
            "level": module_log_level("django.server"),
            "propagate": False,
        },
        "django.db.backends": {
            "handlers": ["console"],
            "level": "DEBUG"
            if DJANGO_LOG_SQL
            else module_log_level("django.db.backends"),
            "propagate": False,
        },
    },
}
